-- 036_alphabet_lesson_content.sql
-- Rebuilds l0 (Alphabet) quiz content to cover all 17 Medumba letters whose
-- example word has a confirmed real speaker recording (cross-checked against
-- medumbaAudio.js's STORAGE_FILES/WORD_CLIPS + single-syllable fallback).
-- The other 16 letters in the alphabet (a, ε, c, d, e, ə, h, i, j, ŋ, u, v, w, z)
-- don't have a confirmed real-audio example word yet — flagged for Felix/native
-- speakers, not fabricated here.

delete from public.lesson_questions where lesson_id = 'l0';

insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 0, '{"type":"meaning","audio":"Mα̂","answer":"α","options":["α","f","m","s"],"answerFr":"α","optionsFr":["α","f","m","s"],"sourceFr":"Lettre de \"Mα̂\" ?","sourceEn":"Letter in \"Mα̂\"?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 1, '{"type":"meaning","audio":"Baꞌ","answer":"b","options":["b","k","o","ts"],"answerFr":"b","optionsFr":["b","k","o","ts"],"sourceFr":"Lettre de \"Baꞌ\" ?","sourceEn":"Letter in \"Baꞌ\"?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 2, '{"type":"meaning","audio":"Fomə","answer":"f","options":["f","n","sh","b"],"answerFr":"f","optionsFr":["f","n","sh","b"],"sourceFr":"Lettre de \"Fomə\" ?","sourceEn":"Letter in \"Fomə\"?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 3, '{"type":"meaning","audio":"Ngàb","answer":"g","options":["g","ɔ","ɨ","k"],"answerFr":"g","optionsFr":["g","ɔ","ɨ","k"],"sourceFr":"Lettre de \"Ngàb\" ?","sourceEn":"Letter in \"Ngàb\"?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 4, '{"type":"meaning","audio":"Ghom","answer":"gh","options":["gh","t","f","n"],"answerFr":"gh","optionsFr":["gh","t","f","n"],"sourceFr":"Lettre de \"Ghom\" ?","sourceEn":"Letter in \"Ghom\"?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 5, '{"type":"meaning","audio":"Nkwǐ","answer":"k","options":["k","α","l","ɔ"],"answerFr":"k","optionsFr":["k","α","l","ɔ"],"sourceFr":"Lettre de \"Nkwǐ\" ?","sourceEn":"Letter in \"Nkwǐ\"?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 6, '{"type":"meaning","audio":"Leꞌe","answer":"l","options":["l","g","ny","t"],"answerFr":"l","optionsFr":["l","g","ny","t"],"sourceFr":"Lettre de \"Leꞌe\" ?","sourceEn":"Letter in \"Leꞌe\"?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 7, '{"type":"meaning","audio":"Mɛn","answer":"m","options":["m","l","s","α"],"answerFr":"m","optionsFr":["m","l","s","α"],"sourceFr":"Lettre de \"Mɛn\" ?","sourceEn":"Letter in \"Mɛn\"?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 8, '{"type":"meaning","audio":"Ntsə","answer":"n","options":["n","o","ts","g"],"answerFr":"n","optionsFr":["n","o","ts","g"],"sourceFr":"Lettre de \"Ntsə\" ?","sourceEn":"Letter in \"Ntsə\"?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 9, '{"type":"meaning","audio":"Nyàm","answer":"ny","options":["ny","sh","b","l"],"answerFr":"ny","optionsFr":["ny","sh","b","l"],"sourceFr":"Lettre de \"Nyàm\" ?","sourceEn":"Letter in \"Nyàm\"?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 10, '{"type":"meaning","audio":"O zi ὰ?","answer":"o","options":["o","ɨ","gh","ny"],"answerFr":"o","optionsFr":["o","ɨ","gh","ny"],"sourceFr":"Lettre de \"O zi ὰ?\" ?","sourceEn":"Letter in \"O zi ὰ?\"?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 11, '{"type":"meaning","audio":"Bɔ","answer":"ɔ","options":["ɔ","f","m","sh"],"answerFr":"ɔ","optionsFr":["ɔ","f","m","sh"],"sourceFr":"Lettre de \"Bɔ\" ?","sourceEn":"Letter in \"Bɔ\"?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 12, '{"type":"meaning","audio":"Saŋə","answer":"s","options":["s","k","o","ɨ"],"answerFr":"s","optionsFr":["s","k","o","ɨ"],"sourceFr":"Lettre de \"Saŋə\" ?","sourceEn":"Letter in \"Saŋə\"?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 13, '{"type":"meaning","audio":"Nshùm","answer":"sh","options":["sh","n","t","f"],"answerFr":"sh","optionsFr":["sh","n","t","f"],"sourceFr":"Lettre de \"Nshùm\" ?","sourceEn":"Letter in \"Nshùm\"?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 14, '{"type":"meaning","audio":"Tα̂","answer":"t","options":["t","ɔ","α","k"],"answerFr":"t","optionsFr":["t","ɔ","α","k"],"sourceFr":"Lettre de \"Tα̂\" ?","sourceEn":"Letter in \"Tα̂\"?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 15, '{"type":"meaning","audio":"Tswəꞌ","answer":"ts","options":["ts","t","g","n"],"answerFr":"ts","optionsFr":["ts","t","g","n"],"sourceFr":"Lettre de \"Tswəꞌ\" ?","sourceEn":"Letter in \"Tswəꞌ\"?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 16, '{"type":"meaning","audio":"Bʉn","answer":"ɨ","options":["ɨ","b","l","ɔ"],"answerFr":"ɨ","optionsFr":["ɨ","b","l","ɔ"],"sourceFr":"Lettre de \"Bʉn\" ?","sourceEn":"Letter in \"Bʉn\"?"}'::jsonb);

insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 0, '{"bank":["α","f","m","s","b","l"],"answer":["α"],"audio":"Mα̂","sourceFr":"Lettre de \"Mα̂\" (mère) ?","sourceEn":"Letter in \"Mα̂\" (mother)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 1, '{"bank":["b","k","o","ts","gh","ny"],"answer":["b"],"audio":"Baꞌ","sourceFr":"Lettre de \"Baꞌ\" (maison) ?","sourceEn":"Letter in \"Baꞌ\" (house)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 2, '{"bank":["f","n","sh","b","m","s"],"answer":["f"],"audio":"Fomə","sourceFr":"Lettre de \"Fomə\" (huit) ?","sourceEn":"Letter in \"Fomə\" (eight)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 3, '{"bank":["g","ɔ","ɨ","k","o","ts"],"answer":["g"],"audio":"Ngàb","sourceFr":"Lettre de \"Ngàb\" (chèvre) ?","sourceEn":"Letter in \"Ngàb\" (goat)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 4, '{"bank":["gh","t","f","n","sh","b"],"answer":["gh"],"audio":"Ghom","sourceFr":"Lettre de \"Ghom\" (corps) ?","sourceEn":"Letter in \"Ghom\" (body)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 5, '{"bank":["k","α","l","ɔ","ɨ","gh"],"answer":["k"],"audio":"Nkwǐ","sourceFr":"Lettre de \"Nkwǐ\" (singe) ?","sourceEn":"Letter in \"Nkwǐ\" (monkey)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 6, '{"bank":["l","g","ny","t","f","n"],"answer":["l"],"audio":"Leꞌe","sourceFr":"Lettre de \"Leꞌe\" (jour) ?","sourceEn":"Letter in \"Leꞌe\" (day)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 7, '{"bank":["m","l","s","α","k","ɔ"],"answer":["m"],"audio":"Mɛn","sourceFr":"Lettre de \"Mɛn\" (enfant) ?","sourceEn":"Letter in \"Mɛn\" (child)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 8, '{"bank":["n","o","ts","g","ny","t"],"answer":["n"],"audio":"Ntsə","sourceFr":"Lettre de \"Ntsə\" (eau) ?","sourceEn":"Letter in \"Ntsə\" (water)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 9, '{"bank":["ny","sh","b","l","s","α"],"answer":["ny"],"audio":"Nyàm","sourceFr":"Lettre de \"Nyàm\" (soleil) ?","sourceEn":"Letter in \"Nyàm\" (sun)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 10, '{"bank":["o","ɨ","gh","ny","ts","g"],"answer":["o"],"audio":"O zi ὰ?","sourceFr":"Lettre de \"O zi ὰ?\" (bonjour) ?","sourceEn":"Letter in \"O zi ὰ?\" (hello)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 11, '{"bank":["ɔ","f","m","sh","b","l"],"answer":["ɔ"],"audio":"Bɔ","sourceFr":"Lettre de \"Bɔ\" (nous) ?","sourceEn":"Letter in \"Bɔ\" (we)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 12, '{"bank":["s","k","o","ɨ","gh","ny"],"answer":["s"],"audio":"Saŋə","sourceFr":"Lettre de \"Saŋə\" (vache) ?","sourceEn":"Letter in \"Saŋə\" (cow)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 13, '{"bank":["sh","n","t","f","m","s"],"answer":["sh"],"audio":"Nshùm","sourceFr":"Lettre de \"Nshùm\" (garçon) ?","sourceEn":"Letter in \"Nshùm\" (boy)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 14, '{"bank":["t","ɔ","α","k","o","ɨ"],"answer":["t"],"audio":"Tα̂","sourceFr":"Lettre de \"Tα̂\" (père) ?","sourceEn":"Letter in \"Tα̂\" (father)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 15, '{"bank":["ts","t","g","n","sh","f"],"answer":["ts"],"audio":"Tswəꞌ","sourceFr":"Lettre de \"Tswəꞌ\" (nuit) ?","sourceEn":"Letter in \"Tswəꞌ\" (night)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 16, '{"bank":["ɨ","b","l","ɔ","α","k"],"answer":["ɨ"],"audio":"Bʉn","sourceFr":"Lettre de \"Bʉn\" (lait) ?","sourceEn":"Letter in \"Bʉn\" (milk)?"}'::jsonb);

insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'match', 0, '{"type":"match","pairs":[{"french":"Mα̂ (mère)","english":"Mα̂ (mother)","medumba":"α"},{"french":"Baꞌ (maison)","english":"Baꞌ (house)","medumba":"b"},{"french":"Fomə (huit)","english":"Fomə (eight)","medumba":"f"},{"french":"Ngàb (chèvre)","english":"Ngàb (goat)","medumba":"g"},{"french":"Ghom (corps)","english":"Ghom (body)","medumba":"gh"},{"french":"Nkwǐ (singe)","english":"Nkwǐ (monkey)","medumba":"k"},{"french":"Leꞌe (jour)","english":"Leꞌe (day)","medumba":"l"},{"french":"Mɛn (enfant)","english":"Mɛn (child)","medumba":"m"},{"french":"Ntsə (eau)","english":"Ntsə (water)","medumba":"n"}]}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'match', 1, '{"type":"match","pairs":[{"french":"Nyàm (soleil)","english":"Nyàm (sun)","medumba":"ny"},{"french":"O zi ὰ? (bonjour)","english":"O zi ὰ? (hello)","medumba":"o"},{"french":"Bɔ (nous)","english":"Bɔ (we)","medumba":"ɔ"},{"french":"Saŋə (vache)","english":"Saŋə (cow)","medumba":"s"},{"french":"Nshùm (garçon)","english":"Nshùm (boy)","medumba":"sh"},{"french":"Tα̂ (père)","english":"Tα̂ (father)","medumba":"t"},{"french":"Tswəꞌ (nuit)","english":"Tswəꞌ (night)","medumba":"ts"},{"french":"Bʉn (lait)","english":"Bʉn (milk)","medumba":"ɨ"}]}'::jsonb);

-- Flashcard preview (shown before the quiz) — same 17 example words, so the
-- preview introduces exactly the letters the quiz will then test.
delete from public.lesson_flashcards where lesson_id = 'l0';

insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'mère', 'Mα̂', 'mother', 0);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'maison', 'Baꞌ', 'house', 1);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'huit', 'Fomə', 'eight', 2);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'chèvre', 'Ngàb', 'goat', 3);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'corps', 'Ghom', 'body', 4);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'singe', 'Nkwǐ', 'monkey', 5);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'jour', 'Leꞌe', 'day', 6);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'enfant', 'Mɛn', 'child', 7);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'eau', 'Ntsə', 'water', 8);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'soleil', 'Nyàm', 'sun', 9);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'bonjour', 'O zi ὰ?', 'hello', 10);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'nous', 'Bɔ', 'we', 11);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'vache', 'Saŋə', 'cow', 12);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'garçon', 'Nshùm', 'boy', 13);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'père', 'Tα̂', 'father', 14);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'nuit', 'Tswəꞌ', 'night', 15);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'lait', 'Bʉn', 'milk', 16);
