-- 037_alphabet_letter_audio.sql
-- Reworks l0 (Alphabet) quiz to use the letter's own isolated-sound
-- recording (src/assets/alphabet/*.mp4, via the new letterAudio.js util)
-- instead of requiring the example word to have its own separate
-- recording. This raises real-audio coverage from 17 to 32 of 33
-- letters (only 'ə' has no recording anywhere, letter or word — it
-- stays text-only in the match questions, which don't need audio).

delete from public.lesson_questions where lesson_id = 'l0';

insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 0, '{"type":"meaning","audioKind":"letter","audio":"a","answer":"a","options":["a","ε","f","j"],"answerFr":"a","optionsFr":["a","ε","f","j"],"sourceFr":"Quelle lettre entendez-vous ? (indice : \"a tə̂\" = et)","sourceEn":"Which letter do you hear? (hint: \"a tə̂\" = and)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 1, '{"type":"meaning","audioKind":"word","audio":"Mα̂","answer":"α","options":["α","d","h","m"],"answerFr":"α","optionsFr":["α","d","h","m"],"sourceFr":"Quelle lettre entendez-vous ? (indice : \"Mα̂\" = mère)","sourceEn":"Which letter do you hear? (hint: \"Mα̂\" = mother)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 2, '{"type":"meaning","audioKind":"letter","audio":"ε","answer":"ε","options":["ε","g","k","ny"],"answerFr":"ε","optionsFr":["ε","g","k","ny"],"sourceFr":"Quelle lettre entendez-vous ? (indice : \"mεn\" = enfant)","sourceEn":"Which letter do you hear? (hint: \"mεn\" = child)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 3, '{"type":"meaning","audioKind":"letter","audio":"b","answer":"b","options":["b","i","n","s"],"answerFr":"b","optionsFr":["b","i","n","s"],"sourceFr":"Quelle lettre entendez-vous ? (indice : \"Baꞌ\" = maison)","sourceEn":"Which letter do you hear? (hint: \"Baꞌ\" = house)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 4, '{"type":"meaning","audioKind":"letter","audio":"c","answer":"c","options":["c","l","o","ts"],"answerFr":"c","optionsFr":["c","l","o","ts"],"sourceFr":"Quelle lettre entendez-vous ? (indice : \"cα̂ꞌ\" = chien)","sourceEn":"Which letter do you hear? (hint: \"cα̂ꞌ\" = dog)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 5, '{"type":"meaning","audioKind":"letter","audio":"d","answer":"d","options":["d","ŋ","sh","v"],"answerFr":"d","optionsFr":["d","ŋ","sh","v"],"sourceFr":"Quelle lettre entendez-vous ? (indice : \"ndα\" = main)","sourceEn":"Which letter do you hear? (hint: \"ndα\" = hand)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 6, '{"type":"meaning","audioKind":"letter","audio":"e","answer":"e","options":["e","ɔ","u","z"],"answerFr":"e","optionsFr":["e","ɔ","u","z"],"sourceFr":"Quelle lettre entendez-vous ? (indice : \"meꞌe\" = chèvre)","sourceEn":"Which letter do you hear? (hint: \"meꞌe\" = goat)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 7, '{"type":"meaning","audioKind":"letter","audio":"f","answer":"f","options":["f","t","w","α"],"answerFr":"f","optionsFr":["f","t","w","α"],"sourceFr":"Quelle lettre entendez-vous ? (indice : \"Fomə\" = huit)","sourceEn":"Which letter do you hear? (hint: \"Fomə\" = eight)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 8, '{"type":"meaning","audioKind":"letter","audio":"g","answer":"g","options":["g","ɨ","ꞌ","c"],"answerFr":"g","optionsFr":["g","ɨ","ꞌ","c"],"sourceFr":"Quelle lettre entendez-vous ? (indice : \"Ngàb\" = chèvre)","sourceEn":"Which letter do you hear? (hint: \"Ngàb\" = goat)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 9, '{"type":"meaning","audioKind":"letter","audio":"gh","answer":"gh","options":["gh","y","ε","f"],"answerFr":"gh","optionsFr":["gh","y","ε","f"],"sourceFr":"Quelle lettre entendez-vous ? (indice : \"ghom\" = corps)","sourceEn":"Which letter do you hear? (hint: \"ghom\" = body)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 10, '{"type":"meaning","audioKind":"letter","audio":"h","answer":"h","options":["h","a","d","i"],"answerFr":"h","optionsFr":["h","a","d","i"],"sourceFr":"Quelle lettre entendez-vous ? (indice : \"hàm\" = bouche)","sourceEn":"Which letter do you hear? (hint: \"hàm\" = mouth)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 11, '{"type":"meaning","audioKind":"letter","audio":"i","answer":"i","options":["i","b","g","l"],"answerFr":"i","optionsFr":["i","b","g","l"],"sourceFr":"Quelle lettre entendez-vous ? (indice : \"ŋgi\" = arbre)","sourceEn":"Which letter do you hear? (hint: \"ŋgi\" = tree)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 12, '{"type":"meaning","audioKind":"letter","audio":"j","answer":"j","options":["j","e","i","ŋ"],"answerFr":"j","optionsFr":["j","e","i","ŋ"],"sourceFr":"Quelle lettre entendez-vous ? (indice : \"jàm\" = guerre)","sourceEn":"Which letter do you hear? (hint: \"jàm\" = war)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 13, '{"type":"meaning","audioKind":"letter","audio":"k","answer":"k","options":["k","gh","m","ɔ"],"answerFr":"k","optionsFr":["k","gh","m","ɔ"],"sourceFr":"Quelle lettre entendez-vous ? (indice : \"Nkwǐ\" = singe)","sourceEn":"Which letter do you hear? (hint: \"Nkwǐ\" = monkey)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 14, '{"type":"meaning","audioKind":"letter","audio":"l","answer":"l","options":["l","j","ny","t"],"answerFr":"l","optionsFr":["l","j","ny","t"],"sourceFr":"Quelle lettre entendez-vous ? (indice : \"Leꞌe\" = jour)","sourceEn":"Which letter do you hear? (hint: \"Leꞌe\" = day)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 15, '{"type":"meaning","audioKind":"letter","audio":"m","answer":"m","options":["m","n","s","ɨ"],"answerFr":"m","optionsFr":["m","n","s","ɨ"],"sourceFr":"Quelle lettre entendez-vous ? (indice : \"Mɛn\" = enfant)","sourceEn":"Which letter do you hear? (hint: \"Mɛn\" = child)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 16, '{"type":"meaning","audioKind":"letter","audio":"n","answer":"n","options":["n","o","ts","y"],"answerFr":"n","optionsFr":["n","o","ts","y"],"sourceFr":"Quelle lettre entendez-vous ? (indice : \"Ntsə\" = eau)","sourceEn":"Which letter do you hear? (hint: \"Ntsə\" = water)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 17, '{"type":"meaning","audioKind":"letter","audio":"ŋ","answer":"ŋ","options":["ŋ","sh","v","a"],"answerFr":"ŋ","optionsFr":["ŋ","sh","v","a"],"sourceFr":"Quelle lettre entendez-vous ? (indice : \"ŋgi\" = arbre)","sourceEn":"Which letter do you hear? (hint: \"ŋgi\" = tree)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 18, '{"type":"meaning","audioKind":"letter","audio":"ny","answer":"ny","options":["ny","u","z","b"],"answerFr":"ny","optionsFr":["ny","u","z","b"],"sourceFr":"Quelle lettre entendez-vous ? (indice : \"Nyàm\" = soleil)","sourceEn":"Which letter do you hear? (hint: \"Nyàm\" = sun)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 19, '{"type":"meaning","audioKind":"letter","audio":"o","answer":"o","options":["o","w","α","e"],"answerFr":"o","optionsFr":["o","w","α","e"],"sourceFr":"Quelle lettre entendez-vous ? (indice : \"O zi ὰ?\" = bonjour)","sourceEn":"Which letter do you hear? (hint: \"O zi ὰ?\" = hello)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 20, '{"type":"meaning","audioKind":"letter","audio":"ɔ","answer":"ɔ","options":["ɔ","ꞌ","c","gh"],"answerFr":"ɔ","optionsFr":["ɔ","ꞌ","c","gh"],"sourceFr":"Quelle lettre entendez-vous ? (indice : \"Bɔ\" = nous)","sourceEn":"Which letter do you hear? (hint: \"Bɔ\" = we)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 21, '{"type":"meaning","audioKind":"letter","audio":"s","answer":"s","options":["s","ε","f","j"],"answerFr":"s","optionsFr":["s","ε","f","j"],"sourceFr":"Quelle lettre entendez-vous ? (indice : \"Saŋə\" = vache)","sourceEn":"Which letter do you hear? (hint: \"Saŋə\" = cow)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 22, '{"type":"meaning","audioKind":"letter","audio":"sh","answer":"sh","options":["sh","d","h","m"],"answerFr":"sh","optionsFr":["sh","d","h","m"],"sourceFr":"Quelle lettre entendez-vous ? (indice : \"Nshùm\" = garçon)","sourceEn":"Which letter do you hear? (hint: \"Nshùm\" = boy)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 23, '{"type":"meaning","audioKind":"letter","audio":"t","answer":"t","options":["t","g","k","ny"],"answerFr":"t","optionsFr":["t","g","k","ny"],"sourceFr":"Quelle lettre entendez-vous ? (indice : \"Tα̂\" = père)","sourceEn":"Which letter do you hear? (hint: \"Tα̂\" = father)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 24, '{"type":"meaning","audioKind":"letter","audio":"ts","answer":"ts","options":["ts","i","n","s"],"answerFr":"ts","optionsFr":["ts","i","n","s"],"sourceFr":"Quelle lettre entendez-vous ? (indice : \"Tswəꞌ\" = nuit)","sourceEn":"Which letter do you hear? (hint: \"Tswəꞌ\" = night)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 25, '{"type":"meaning","audioKind":"letter","audio":"u","answer":"u","options":["u","l","o","ts"],"answerFr":"u","optionsFr":["u","l","o","ts"],"sourceFr":"Quelle lettre entendez-vous ? (indice : \"ntu\" = tête)","sourceEn":"Which letter do you hear? (hint: \"ntu\" = head)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 26, '{"type":"meaning","audioKind":"letter","audio":"ɨ","answer":"ɨ","options":["ɨ","ŋ","sh","w"],"answerFr":"ɨ","optionsFr":["ɨ","ŋ","sh","w"],"sourceFr":"Quelle lettre entendez-vous ? (indice : \"Bʉn\" = lait)","sourceEn":"Which letter do you hear? (hint: \"Bʉn\" = milk)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 27, '{"type":"meaning","audioKind":"letter","audio":"v","answer":"v","options":["v","ɔ","u","ꞌ"],"answerFr":"v","optionsFr":["v","ɔ","u","ꞌ"],"sourceFr":"Quelle lettre entendez-vous ? (indice : \"vwɔ\" = vous)","sourceEn":"Which letter do you hear? (hint: \"vwɔ\" = you (pl.))"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 28, '{"type":"meaning","audioKind":"letter","audio":"w","answer":"w","options":["w","t","y","ε"],"answerFr":"w","optionsFr":["w","t","y","ε"],"sourceFr":"Quelle lettre entendez-vous ? (indice : \"wud\" = nuit)","sourceEn":"Which letter do you hear? (hint: \"wud\" = night)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 29, '{"type":"meaning","audioKind":"letter","audio":"y","answer":"y","options":["y","ɨ","a","d"],"answerFr":"y","optionsFr":["y","ɨ","a","d"],"sourceFr":"Quelle lettre entendez-vous ? (indice : \"Nyàm\" = soleil)","sourceEn":"Which letter do you hear? (hint: \"Nyàm\" = sun)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 30, '{"type":"meaning","audioKind":"letter","audio":"z","answer":"z","options":["z","y","b","g"],"answerFr":"z","optionsFr":["z","y","b","g"],"sourceFr":"Quelle lettre entendez-vous ? (indice : \"zα\" = moi)","sourceEn":"Which letter do you hear? (hint: \"zα\" = me)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 31, '{"type":"meaning","audioKind":"letter","audio":"ꞌ","answer":"ꞌ","options":["ꞌ","α","e","i"],"answerFr":"ꞌ","optionsFr":["ꞌ","α","e","i"],"sourceFr":"Quelle lettre entendez-vous ? (indice : \"Baꞌ\" = maison)","sourceEn":"Which letter do you hear? (hint: \"Baꞌ\" = house)"}'::jsonb);

insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 0, '{"bank":["a","ε","f","j","ŋ","sh"],"answer":["a"],"audioKind":"letter","audio":"a","sourceFr":"Quelle lettre entendez-vous ? (indice : \"a tə̂\" = et)","sourceEn":"Which letter do you hear? (hint: \"a tə̂\" = and)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 1, '{"bank":["α","d","h","m","ɔ","u"],"answer":["α"],"audioKind":"word","audio":"Mα̂","sourceFr":"Quelle lettre entendez-vous ? (indice : \"Mα̂\" = mère)","sourceEn":"Which letter do you hear? (hint: \"Mα̂\" = mother)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 2, '{"bank":["ε","g","k","ny","t","w"],"answer":["ε"],"audioKind":"letter","audio":"ε","sourceFr":"Quelle lettre entendez-vous ? (indice : \"mεn\" = enfant)","sourceEn":"Which letter do you hear? (hint: \"mεn\" = child)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 3, '{"bank":["b","i","n","s","ɨ","ꞌ"],"answer":["b"],"audioKind":"letter","audio":"b","sourceFr":"Quelle lettre entendez-vous ? (indice : \"Baꞌ\" = maison)","sourceEn":"Which letter do you hear? (hint: \"Baꞌ\" = house)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 4, '{"bank":["c","l","o","ts","y","ε"],"answer":["c"],"audioKind":"letter","audio":"c","sourceFr":"Quelle lettre entendez-vous ? (indice : \"cα̂ꞌ\" = chien)","sourceEn":"Which letter do you hear? (hint: \"cα̂ꞌ\" = dog)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 5, '{"bank":["d","ŋ","sh","v","a","e"],"answer":["d"],"audioKind":"letter","audio":"d","sourceFr":"Quelle lettre entendez-vous ? (indice : \"ndα\" = main)","sourceEn":"Which letter do you hear? (hint: \"ndα\" = hand)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 6, '{"bank":["e","ɔ","u","z","b","gh"],"answer":["e"],"audioKind":"letter","audio":"e","sourceFr":"Quelle lettre entendez-vous ? (indice : \"meꞌe\" = chèvre)","sourceEn":"Which letter do you hear? (hint: \"meꞌe\" = goat)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 7, '{"bank":["f","t","w","α","e","j"],"answer":["f"],"audioKind":"letter","audio":"f","sourceFr":"Quelle lettre entendez-vous ? (indice : \"Fomə\" = huit)","sourceEn":"Which letter do you hear? (hint: \"Fomə\" = eight)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 8, '{"bank":["g","ɨ","ꞌ","c","h","m"],"answer":["g"],"audioKind":"letter","audio":"g","sourceFr":"Quelle lettre entendez-vous ? (indice : \"Ngàb\" = chèvre)","sourceEn":"Which letter do you hear? (hint: \"Ngàb\" = goat)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 9, '{"bank":["gh","y","ε","f","k","ny"],"answer":["gh"],"audioKind":"letter","audio":"gh","sourceFr":"Quelle lettre entendez-vous ? (indice : \"ghom\" = corps)","sourceEn":"Which letter do you hear? (hint: \"ghom\" = body)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 10, '{"bank":["h","a","d","i","n","s"],"answer":["h"],"audioKind":"letter","audio":"h","sourceFr":"Quelle lettre entendez-vous ? (indice : \"hàm\" = bouche)","sourceEn":"Which letter do you hear? (hint: \"hàm\" = mouth)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 11, '{"bank":["i","b","g","l","o","ts"],"answer":["i"],"audioKind":"letter","audio":"i","sourceFr":"Quelle lettre entendez-vous ? (indice : \"ŋgi\" = arbre)","sourceEn":"Which letter do you hear? (hint: \"ŋgi\" = tree)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 12, '{"bank":["j","e","i","ŋ","sh","v"],"answer":["j"],"audioKind":"letter","audio":"j","sourceFr":"Quelle lettre entendez-vous ? (indice : \"jàm\" = guerre)","sourceEn":"Which letter do you hear? (hint: \"jàm\" = war)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 13, '{"bank":["k","gh","m","ɔ","u","z"],"answer":["k"],"audioKind":"letter","audio":"k","sourceFr":"Quelle lettre entendez-vous ? (indice : \"Nkwǐ\" = singe)","sourceEn":"Which letter do you hear? (hint: \"Nkwǐ\" = monkey)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 14, '{"bank":["l","j","ny","t","w","α"],"answer":["l"],"audioKind":"letter","audio":"l","sourceFr":"Quelle lettre entendez-vous ? (indice : \"Leꞌe\" = jour)","sourceEn":"Which letter do you hear? (hint: \"Leꞌe\" = day)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 15, '{"bank":["m","n","s","ɨ","ꞌ","c"],"answer":["m"],"audioKind":"letter","audio":"m","sourceFr":"Quelle lettre entendez-vous ? (indice : \"Mɛn\" = enfant)","sourceEn":"Which letter do you hear? (hint: \"Mɛn\" = child)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 16, '{"bank":["n","o","ts","y","ε","f"],"answer":["n"],"audioKind":"letter","audio":"n","sourceFr":"Quelle lettre entendez-vous ? (indice : \"Ntsə\" = eau)","sourceEn":"Which letter do you hear? (hint: \"Ntsə\" = water)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 17, '{"bank":["ŋ","sh","v","a","d","h"],"answer":["ŋ"],"audioKind":"letter","audio":"ŋ","sourceFr":"Quelle lettre entendez-vous ? (indice : \"ŋgi\" = arbre)","sourceEn":"Which letter do you hear? (hint: \"ŋgi\" = tree)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 18, '{"bank":["ny","u","z","b","g","k"],"answer":["ny"],"audioKind":"letter","audio":"ny","sourceFr":"Quelle lettre entendez-vous ? (indice : \"Nyàm\" = soleil)","sourceEn":"Which letter do you hear? (hint: \"Nyàm\" = sun)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 19, '{"bank":["o","w","α","e","i","n"],"answer":["o"],"audioKind":"letter","audio":"o","sourceFr":"Quelle lettre entendez-vous ? (indice : \"O zi ὰ?\" = bonjour)","sourceEn":"Which letter do you hear? (hint: \"O zi ὰ?\" = hello)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 20, '{"bank":["ɔ","ꞌ","c","gh","l","o"],"answer":["ɔ"],"audioKind":"letter","audio":"ɔ","sourceFr":"Quelle lettre entendez-vous ? (indice : \"Bɔ\" = nous)","sourceEn":"Which letter do you hear? (hint: \"Bɔ\" = we)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 21, '{"bank":["s","ε","f","j","ŋ","t"],"answer":["s"],"audioKind":"letter","audio":"s","sourceFr":"Quelle lettre entendez-vous ? (indice : \"Saŋə\" = vache)","sourceEn":"Which letter do you hear? (hint: \"Saŋə\" = cow)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 22, '{"bank":["sh","d","h","m","ɔ","ɨ"],"answer":["sh"],"audioKind":"letter","audio":"sh","sourceFr":"Quelle lettre entendez-vous ? (indice : \"Nshùm\" = garçon)","sourceEn":"Which letter do you hear? (hint: \"Nshùm\" = boy)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 23, '{"bank":["t","g","k","ny","ts","y"],"answer":["t"],"audioKind":"letter","audio":"t","sourceFr":"Quelle lettre entendez-vous ? (indice : \"Tα̂\" = père)","sourceEn":"Which letter do you hear? (hint: \"Tα̂\" = father)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 24, '{"bank":["ts","i","n","s","v","a"],"answer":["ts"],"audioKind":"letter","audio":"ts","sourceFr":"Quelle lettre entendez-vous ? (indice : \"Tswəꞌ\" = nuit)","sourceEn":"Which letter do you hear? (hint: \"Tswəꞌ\" = night)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 25, '{"bank":["u","l","o","ts","z","b"],"answer":["u"],"audioKind":"letter","audio":"u","sourceFr":"Quelle lettre entendez-vous ? (indice : \"ntu\" = tête)","sourceEn":"Which letter do you hear? (hint: \"ntu\" = head)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 26, '{"bank":["ɨ","ŋ","sh","w","α","e"],"answer":["ɨ"],"audioKind":"letter","audio":"ɨ","sourceFr":"Quelle lettre entendez-vous ? (indice : \"Bʉn\" = lait)","sourceEn":"Which letter do you hear? (hint: \"Bʉn\" = milk)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 27, '{"bank":["v","ɔ","u","ꞌ","c","gh"],"answer":["v"],"audioKind":"letter","audio":"v","sourceFr":"Quelle lettre entendez-vous ? (indice : \"vwɔ\" = vous)","sourceEn":"Which letter do you hear? (hint: \"vwɔ\" = you (pl.))"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 28, '{"bank":["w","t","y","ε","f","j"],"answer":["w"],"audioKind":"letter","audio":"w","sourceFr":"Quelle lettre entendez-vous ? (indice : \"wud\" = nuit)","sourceEn":"Which letter do you hear? (hint: \"wud\" = night)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 29, '{"bank":["y","ɨ","a","d","h","m"],"answer":["y"],"audioKind":"letter","audio":"y","sourceFr":"Quelle lettre entendez-vous ? (indice : \"Nyàm\" = soleil)","sourceEn":"Which letter do you hear? (hint: \"Nyàm\" = sun)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 30, '{"bank":["z","y","b","g","k","ny"],"answer":["z"],"audioKind":"letter","audio":"z","sourceFr":"Quelle lettre entendez-vous ? (indice : \"zα\" = moi)","sourceEn":"Which letter do you hear? (hint: \"zα\" = me)"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'tile', 31, '{"bank":["ꞌ","α","e","i","n","s"],"answer":["ꞌ"],"audioKind":"letter","audio":"ꞌ","sourceFr":"Quelle lettre entendez-vous ? (indice : \"Baꞌ\" = maison)","sourceEn":"Which letter do you hear? (hint: \"Baꞌ\" = house)"}'::jsonb);

insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'match', 0, '{"type":"match","pairs":[{"french":"a tə̂ (et)","english":"a tə̂ (and)","medumba":"a"},{"french":"Mα̂ (mère)","english":"Mα̂ (mother)","medumba":"α"},{"french":"mεn (enfant)","english":"mεn (child)","medumba":"ε"},{"french":"Baꞌ (maison)","english":"Baꞌ (house)","medumba":"b"},{"french":"cα̂ꞌ (chien)","english":"cα̂ꞌ (dog)","medumba":"c"},{"french":"ndα (main)","english":"ndα (hand)","medumba":"d"},{"french":"meꞌe (chèvre)","english":"meꞌe (goat)","medumba":"e"},{"french":"bwə̀ꞌə (neuf)","english":"bwə̀ꞌə (nine)","medumba":"ə"},{"french":"Fomə (huit)","english":"Fomə (eight)","medumba":"f"}]}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'match', 1, '{"type":"match","pairs":[{"french":"Ngàb (chèvre)","english":"Ngàb (goat)","medumba":"g"},{"french":"ghom (corps)","english":"ghom (body)","medumba":"gh"},{"french":"hàm (bouche)","english":"hàm (mouth)","medumba":"h"},{"french":"ŋgi (arbre)","english":"ŋgi (tree)","medumba":"i"},{"french":"jàm (guerre)","english":"jàm (war)","medumba":"j"},{"french":"Nkwǐ (singe)","english":"Nkwǐ (monkey)","medumba":"k"},{"french":"Leꞌe (jour)","english":"Leꞌe (day)","medumba":"l"},{"french":"Mɛn (enfant)","english":"Mɛn (child)","medumba":"m"},{"french":"Ntsə (eau)","english":"Ntsə (water)","medumba":"n"}]}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'match', 2, '{"type":"match","pairs":[{"french":"ŋgi (arbre)","english":"ŋgi (tree)","medumba":"ŋ"},{"french":"Nyàm (soleil)","english":"Nyàm (sun)","medumba":"ny"},{"french":"O zi ὰ? (bonjour)","english":"O zi ὰ? (hello)","medumba":"o"},{"french":"Bɔ (nous)","english":"Bɔ (we)","medumba":"ɔ"},{"french":"Saŋə (vache)","english":"Saŋə (cow)","medumba":"s"},{"french":"Nshùm (garçon)","english":"Nshùm (boy)","medumba":"sh"},{"french":"Tα̂ (père)","english":"Tα̂ (father)","medumba":"t"},{"french":"Tswəꞌ (nuit)","english":"Tswəꞌ (night)","medumba":"ts"},{"french":"ntu (tête)","english":"ntu (head)","medumba":"u"}]}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'match', 3, '{"type":"match","pairs":[{"french":"Bʉn (lait)","english":"Bʉn (milk)","medumba":"ɨ"},{"french":"vwɔ (vous)","english":"vwɔ (you (pl.))","medumba":"v"},{"french":"wud (nuit)","english":"wud (night)","medumba":"w"},{"french":"Nyàm (soleil)","english":"Nyàm (sun)","medumba":"y"},{"french":"zα (moi)","english":"zα (me)","medumba":"z"},{"french":"Baꞌ (maison)","english":"Baꞌ (house)","medumba":"ꞌ"}]}'::jsonb);

delete from public.lesson_flashcards where lesson_id = 'l0';
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'et', 'a tə̂', 'and', 0);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'mère', 'Mα̂', 'mother', 1);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'enfant', 'mεn', 'child', 2);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'maison', 'Baꞌ', 'house', 3);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'chien', 'cα̂ꞌ', 'dog', 4);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'main', 'ndα', 'hand', 5);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'chèvre', 'meꞌe', 'goat', 6);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'neuf', 'bwə̀ꞌə', 'nine', 7);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'huit', 'Fomə', 'eight', 8);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'chèvre', 'Ngàb', 'goat', 9);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'corps', 'ghom', 'body', 10);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'bouche', 'hàm', 'mouth', 11);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'arbre', 'ŋgi', 'tree', 12);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'guerre', 'jàm', 'war', 13);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'singe', 'Nkwǐ', 'monkey', 14);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'jour', 'Leꞌe', 'day', 15);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'enfant', 'Mɛn', 'child', 16);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'eau', 'Ntsə', 'water', 17);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'arbre', 'ŋgi', 'tree', 18);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'soleil', 'Nyàm', 'sun', 19);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'bonjour', 'O zi ὰ?', 'hello', 20);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'nous', 'Bɔ', 'we', 21);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'vache', 'Saŋə', 'cow', 22);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'garçon', 'Nshùm', 'boy', 23);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'père', 'Tα̂', 'father', 24);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'nuit', 'Tswəꞌ', 'night', 25);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'tête', 'ntu', 'head', 26);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'lait', 'Bʉn', 'milk', 27);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'vous', 'vwɔ', 'you (pl.)', 28);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'nuit', 'wud', 'night', 29);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'soleil', 'Nyàm', 'sun', 30);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'moi', 'zα', 'me', 31);
insert into public.lesson_flashcards (lesson_id, expression_fr, expression_medumba, expression_en, order_index) values ('l0', 'maison', 'Baꞌ', 'house', 32);
