-- 038_fix_alphabet_meaning_questions.sql
-- migration 037 mistakenly phrased l0's 'meaning' questions as
-- listening exercises ("Quelle lettre entendez-vous ?"), but the
-- 'meaning' question type has no audio button anywhere in LessonPage.jsx
-- (only 'tile'/'audio'/'image_vocab' do) — it's pure text: the word is
-- shown as a written prompt, no listening involved. Reverts to reading-
-- based phrasing (as in migration 036) and, since there's no audio
-- constraint on a text-only question, expands to all 33 letters instead
-- of stopping at 32. 'tile' questions (which DO have a play button) keep
-- migration 037's letter-audio approach unchanged.

delete from public.lesson_questions where lesson_id = 'l0' and question_type = 'meaning';

insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 0, '{"type":"meaning","answer":"a","options":["a","ε","ə","i"],"answerFr":"a","optionsFr":["a","ε","ə","i"],"sourceFr":"Lettre de \"a tə̂\" (et) ?","sourceEn":"Letter in \"a tə̂\" (and)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 1, '{"type":"meaning","answer":"α","options":["α","d","gh","l"],"answerFr":"α","optionsFr":["α","d","gh","l"],"sourceFr":"Lettre de \"Mα̂\" (mère) ?","sourceEn":"Letter in \"Mα̂\" (mother)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 2, '{"type":"meaning","answer":"ε","options":["ε","f","j","ŋ"],"answerFr":"ε","optionsFr":["ε","f","j","ŋ"],"sourceFr":"Lettre de \"mεn\" (enfant) ?","sourceEn":"Letter in \"mεn\" (child)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 3, '{"type":"meaning","answer":"b","options":["b","h","m","ɔ"],"answerFr":"b","optionsFr":["b","h","m","ɔ"],"sourceFr":"Lettre de \"Baꞌ\" (maison) ?","sourceEn":"Letter in \"Baꞌ\" (house)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 4, '{"type":"meaning","answer":"c","options":["c","k","ny","t"],"answerFr":"c","optionsFr":["c","k","ny","t"],"sourceFr":"Lettre de \"cα̂ꞌ\" (chien) ?","sourceEn":"Letter in \"cα̂ꞌ\" (dog)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 5, '{"type":"meaning","answer":"d","options":["d","n","s","ɨ"],"answerFr":"d","optionsFr":["d","n","s","ɨ"],"sourceFr":"Lettre de \"ndα\" (main) ?","sourceEn":"Letter in \"ndα\" (hand)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 6, '{"type":"meaning","answer":"e","options":["e","o","ts","y"],"answerFr":"e","optionsFr":["e","o","ts","y"],"sourceFr":"Lettre de \"meꞌe\" (chèvre) ?","sourceEn":"Letter in \"meꞌe\" (goat)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 7, '{"type":"meaning","answer":"ə","options":["ə","sh","v","a"],"answerFr":"ə","optionsFr":["ə","sh","v","a"],"sourceFr":"Lettre de \"bwə̀ꞌə\" (neuf) ?","sourceEn":"Letter in \"bwə̀ꞌə\" (nine)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 8, '{"type":"meaning","answer":"f","options":["f","u","z","b"],"answerFr":"f","optionsFr":["f","u","z","b"],"sourceFr":"Lettre de \"Fomə\" (huit) ?","sourceEn":"Letter in \"Fomə\" (eight)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 9, '{"type":"meaning","answer":"g","options":["g","w","α","e"],"answerFr":"g","optionsFr":["g","w","α","e"],"sourceFr":"Lettre de \"Ngàb\" (chèvre) ?","sourceEn":"Letter in \"Ngàb\" (goat)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 10, '{"type":"meaning","answer":"gh","options":["gh","ꞌ","c","g"],"answerFr":"gh","optionsFr":["gh","ꞌ","c","g"],"sourceFr":"Lettre de \"ghom\" (corps) ?","sourceEn":"Letter in \"ghom\" (body)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 11, '{"type":"meaning","answer":"h","options":["h","ε","ə","j"],"answerFr":"h","optionsFr":["h","ε","ə","j"],"sourceFr":"Lettre de \"hàm\" (bouche) ?","sourceEn":"Letter in \"hàm\" (mouth)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 12, '{"type":"meaning","answer":"i","options":["i","d","gh","m"],"answerFr":"i","optionsFr":["i","d","gh","m"],"sourceFr":"Lettre de \"ŋgi\" (arbre) ?","sourceEn":"Letter in \"ŋgi\" (tree)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 13, '{"type":"meaning","answer":"j","options":["j","f","k","ny"],"answerFr":"j","optionsFr":["j","f","k","ny"],"sourceFr":"Lettre de \"jàm\" (guerre) ?","sourceEn":"Letter in \"jàm\" (war)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 14, '{"type":"meaning","answer":"k","options":["k","h","n","s"],"answerFr":"k","optionsFr":["k","h","n","s"],"sourceFr":"Lettre de \"Nkwǐ\" (singe) ?","sourceEn":"Letter in \"Nkwǐ\" (monkey)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 15, '{"type":"meaning","answer":"l","options":["l","k","o","ts"],"answerFr":"l","optionsFr":["l","k","o","ts"],"sourceFr":"Lettre de \"Leꞌe\" (jour) ?","sourceEn":"Letter in \"Leꞌe\" (day)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 16, '{"type":"meaning","answer":"m","options":["m","ŋ","sh","v"],"answerFr":"m","optionsFr":["m","ŋ","sh","v"],"sourceFr":"Lettre de \"Mɛn\" (enfant) ?","sourceEn":"Letter in \"Mɛn\" (child)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 17, '{"type":"meaning","answer":"n","options":["n","ɔ","u","z"],"answerFr":"n","optionsFr":["n","ɔ","u","z"],"sourceFr":"Lettre de \"Ntsə\" (eau) ?","sourceEn":"Letter in \"Ntsə\" (water)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 18, '{"type":"meaning","answer":"ŋ","options":["ŋ","t","w","α"],"answerFr":"ŋ","optionsFr":["ŋ","t","w","α"],"sourceFr":"Lettre de \"ŋgi\" (arbre) ?","sourceEn":"Letter in \"ŋgi\" (tree)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 19, '{"type":"meaning","answer":"ny","options":["ny","ɨ","ꞌ","c"],"answerFr":"ny","optionsFr":["ny","ɨ","ꞌ","c"],"sourceFr":"Lettre de \"Nyàm\" (soleil) ?","sourceEn":"Letter in \"Nyàm\" (sun)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 20, '{"type":"meaning","answer":"o","options":["o","y","ε","ə"],"answerFr":"o","optionsFr":["o","y","ε","ə"],"sourceFr":"Lettre de \"O zi ὰ?\" (bonjour) ?","sourceEn":"Letter in \"O zi ὰ?\" (hello)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 21, '{"type":"meaning","answer":"ɔ","options":["ɔ","a","d","gh"],"answerFr":"ɔ","optionsFr":["ɔ","a","d","gh"],"sourceFr":"Lettre de \"Bɔ\" (nous) ?","sourceEn":"Letter in \"Bɔ\" (we)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 22, '{"type":"meaning","answer":"s","options":["s","b","f","j"],"answerFr":"s","optionsFr":["s","b","f","j"],"sourceFr":"Lettre de \"Saŋə\" (vache) ?","sourceEn":"Letter in \"Saŋə\" (cow)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 23, '{"type":"meaning","answer":"sh","options":["sh","e","h","m"],"answerFr":"sh","optionsFr":["sh","e","h","m"],"sourceFr":"Lettre de \"Nshùm\" (garçon) ?","sourceEn":"Letter in \"Nshùm\" (boy)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 24, '{"type":"meaning","answer":"t","options":["t","g","k","ny"],"answerFr":"t","optionsFr":["t","g","k","ny"],"sourceFr":"Lettre de \"Tα̂\" (père) ?","sourceEn":"Letter in \"Tα̂\" (father)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 25, '{"type":"meaning","answer":"ts","options":["ts","i","n","s"],"answerFr":"ts","optionsFr":["ts","i","n","s"],"sourceFr":"Lettre de \"Tswəꞌ\" (nuit) ?","sourceEn":"Letter in \"Tswəꞌ\" (night)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 26, '{"type":"meaning","answer":"u","options":["u","l","o","ts"],"answerFr":"u","optionsFr":["u","l","o","ts"],"sourceFr":"Lettre de \"ntu\" (tête) ?","sourceEn":"Letter in \"ntu\" (head)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 27, '{"type":"meaning","answer":"ɨ","options":["ɨ","ŋ","sh","w"],"answerFr":"ɨ","optionsFr":["ɨ","ŋ","sh","w"],"sourceFr":"Lettre de \"Bʉn\" (lait) ?","sourceEn":"Letter in \"Bʉn\" (milk)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 28, '{"type":"meaning","answer":"v","options":["v","ɔ","u","ꞌ"],"answerFr":"v","optionsFr":["v","ɔ","u","ꞌ"],"sourceFr":"Lettre de \"vwɔ\" (vous) ?","sourceEn":"Letter in \"vwɔ\" (you (pl.))?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 29, '{"type":"meaning","answer":"w","options":["w","t","y","ε"],"answerFr":"w","optionsFr":["w","t","y","ε"],"sourceFr":"Lettre de \"wud\" (nuit) ?","sourceEn":"Letter in \"wud\" (night)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 30, '{"type":"meaning","answer":"y","options":["y","ɨ","a","d"],"answerFr":"y","optionsFr":["y","ɨ","a","d"],"sourceFr":"Lettre de \"Nyàm\" (soleil) ?","sourceEn":"Letter in \"Nyàm\" (sun)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 31, '{"type":"meaning","answer":"z","options":["z","y","b","f"],"answerFr":"z","optionsFr":["z","y","b","f"],"sourceFr":"Lettre de \"zα\" (moi) ?","sourceEn":"Letter in \"zα\" (me)?"}'::jsonb);
insert into public.lesson_questions (lesson_id, question_type, order_index, payload) values ('l0', 'meaning', 32, '{"type":"meaning","answer":"ꞌ","options":["ꞌ","α","e","h"],"answerFr":"ꞌ","optionsFr":["ꞌ","α","e","h"],"sourceFr":"Lettre de \"Baꞌ\" (maison) ?","sourceEn":"Letter in \"Baꞌ\" (house)?"}'::jsonb);
